### ISSUE TITLE
npx npm-force-resolutions errors when installed via yarn

### ISSUE THREAD

**Issue by Julusian** [tap-chris/mamsc#4]
**Describe the bug**
It is not possible to install this libary into a project using yarn. Attempting to do so errors

**To reproduce**
In an empty folder
1) `yarn init -y`
1) `yarn add mamsc`

```
$ yarn add mamsc
yarn add v1.22.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/julus/Projects/companion-build/msc-test/node_modules/mamsc: Command failed.
Exit code: 1
Command: npx npm-force-resolutions
Arguments: 
Directory: /home/julus/Projects/companion-build/msc-test/node_modules/mamsc
Output:
npx: installed 6 in 1.318s
Error: ENOENT: no such file or directory, open './package-lock.json'
    at Object.openSync (fs.js:476:3)
    at Object.fs [as readFileSync] (fs.js:377:35)
    at npm_force_resolutions$core$node_slurp (/home/julus/.npm/_npx/625790/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:15:20)
    at npm_force_resolutions$core$read_json (/home/julus/.npm/_npx/625790/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:22:23)
    at switch__2144__auto__ (/home/julus/.npm/_npx/625790/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3)
    at /home/julus/.npm/_npx/625790/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3
    at npm_force_resolutions$core$update_package_lock_$_state_machine__2145__auto____1 (/home/julus/.npm/_npx/625790/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:648:4)
    at cljs.core.async.impl.ioc-helpers/FN-IDX (/home/julus/.npm/_npx/625790/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:664:88)
    at cljs.core.async.impl.ioc-helpers/run-state-machine (/home/julus/.npm/_npx/625790/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:35:23)
    at cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped (/home/julus/.npm/_npx/625790/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:39:6)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Expected behavior**
It to install cleanly

**Version information**
 - mamsc: 1.0.2
 - Node.js: 14.16.0
 - Platform: linux x64
 - Console: N/A

**Additional context**
`npm-force-resolutions` appears to be used to resolve issues with devDependencies, so is a 'useless' step for library users. The audit can also be fixed by updating the dependencies. Additionally, `npm-force-resolutions` is unlikely to have any effect when installing a library as npm and yarn will ignore lockfiles from dependencies.

**Comment by tap-chris** [comment]
npm-force-resolutions has been removed.
